### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by fsevenm** [SeoFernando25/ulauncher-gpt#3]
It's just `Loading...`. Ulauncher logs this on terminal:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/fsevenm/.local/share/ulauncher/extensions/com.github.seofernando25.ulauncher-gpt/main.py", line 165, in on_event
    item_string = ' | '.join([item.name for item in items])
  File "/home/fsevenm/.local/share/ulauncher/extensions/com.github.seofernando25.ulauncher-gpt/main.py", line 165, in <listcomp>
    item_string = ' | '.join([item.name for item in items])
AttributeError: 'ExtensionResultItem' object has no attribute 'name'
```

**Comment by seofernando25** [comment]
Hmm that is quite strange. In theory, `ExtensionResultItem` should always have the `name` attribute

![image](https://user-images.githubusercontent.com/26195439/228371944-62daa29c-ecdb-416a-9f39-55115388050d.png)

In any case, I'll just add a try/except block as a workaround
